sylius_shop_one_page_checkout:
    path: /{_locale}/one-page-checkout
    methods: [GET, PUT, POST]
    defaults:
        _controller: sylius.controller.order::updateAction
        _sylius:
            template: '@MudrakOnePageCheckoutPlugin/shop/one_page_checkout.html.twig'
            repository:
                method: findOneBy
                arguments:
                    - id: "expr:service('sylius.context.cart').getCart().getId()"
            state_machine:
                graph: sylius_order_checkout
                transition: complete