sylius_twig_hooks:
    hooks:
        one_page_checkout_summary:
            sylius_one_page_checkout_summary:
                component: 'OnePageCheckout:Summary'
                props:
                    orderId: '@=_context.orderId'
                    template: '@MudrakOnePageCheckoutPlugin/components/OnePageCheckout/Summary.html.twig'
        one_page_checkout_payment:
            sylius_one_page_checkout_payment:
                component: 'OnePageCheckout:Payment'
                props:
                    orderId: '@=_context.orderId'
                    template: '@MudrakOnePageCheckoutPlugin/components/OnePageCheckout/Payment.html.twig'
        one_page_checkout_shipment:
            sylius_one_page_checkout_shipment:
                component: 'OnePageCheckout:Shipment'
                props:
                    orderId: '@=_context.orderId'
                    template: '@MudrakOnePageCheckoutPlugin/components/OnePageCheckout/Shipment.html.twig'
        one_page_checkout_complete:
            sylius_one_page_checkout_complete:
                component: 'OnePageCheckout:Complete'
                props:
                    orderId: '@=_context.orderId'
                    template: '@MudrakOnePageCheckoutPlugin/components/OnePageCheckout/Complete.html.twig'